baseURL = "https://www.esmeraldamartinez.dev/"
canonifyURLs = true
relativeURLs = false
languageCode = "en-us"
title = 'Esmeralda Martinez'

[params]
    description = "Cloud Engineer | IAM Specialist | Full-Stack Developer"